chipset = "sdm845"

[bootimg]
base = 0x0
kernel = 0x8000
ramdisk = 0x1000000
second = 0
tags = 0x100
pagesize = 4096

[[device]]
vendor = "oneplus"
model = "enchilada"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "oneplus"
model = "fajita"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "shift"
model = "axolotl"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "ebbg"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "ebbgnt"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "tianma"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "tianmaft"

[[device]]
vendor = "fairphone"
model = "fp4"
chipset = "sm7225"
