chipset = "sdm845"

[bootimg]
base = 0x0
kernel = 0x8000
ramdisk = 0x1000000
second = 0
tags = 0x100
pagesize = 4096

[[device]]
vendor = "oneplus"
model = "enchilada"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "oneplus"
model = "fajita"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "shift"
model = "axolotl"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "ebbg"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "tianma"

[[device]]
vendor = "xiaomi"
model = "polaris"

[[device]]
vendor = "fairphone"
model = "fp4"
chipset = "sm7225"

[[device]]
vendor = "fairphone"
model = "fp5"
chipset = "qcm6490"
bootimg = { version = 2, base = 0x0, kernel = 0x8000, ramdisk = 0x01000000, dtb = 0x01f00000, second = 0x0, tags = 0x100, pagesize = 4096 }

[[device]]
vendor = "nothing"
model = "spacewar"
bootimg = { version = 2, base = 0x0, kernel = 0x8000, ramdisk = 0x01000000, dtb = 0x01f00000, second = 0x0, tags = 0x100, pagesize = 4096 }